import { UserRole } from "@prisma/client";

/**
 * Permission strings follow role.action.resource from user_roles_rbac.md.
 * Safe for client + server (no Next/Prisma imports).
 */
export type Permission = string;

export type Role = UserRole;

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  DONOR: [
    "own_profile.read.update",
    "appointment.schedule",
    "consent.sign",
    "honorarium.read.own",
    "document.upload.own",
    "withdrawal.initiate",
    "ae.report",
  ],
  RECIPIENT: [
    "own_case.read",
    "package.select",
    "consent.sign",
    "profile.browse",
    "payment.pay",
    "invoice.read.own",
    "cycle_status.read.own",
  ],
  CLINIC_DOCTOR: [
    "drf.create",
    "drf.sign",
    "drf.list",
    "drf.view",
    "cycle_outcome.log",
    "cycle.list",
    "cycle.view",
    "cycle.log_event",
    "cohort.view",
    "cohort.edit_disposition",
    "seedscore.view",
    "report.list",
    "report.view.clinical.own_clinic",
    "report.view.finance.own_clinic",
    "report.run.finance.ar_aging",
    "report.export.csv",
    "report.favorite",
  ],
  CLINIC_COORDINATOR: [
    "recipient.create",
    "drf.track",
    "drf.communicate",
    "drf.create",
    "drf.list",
    "drf.view",
    "invoice.list",
    "invoice.view",
    "cycle.list",
    "cycle.view",
    "cycle.log_event",
    "cohort.view",
    "cohort.edit_disposition",
    "seedscore.view",
    "report.list",
    "report.view.clinical.own_clinic",
    "report.view.finance.own_clinic",
    "report.run.finance.ar_aging",
    "report.export.csv",
    "report.favorite",
  ],
  CLINIC_NURSE: [
    "dispatch.receive",
    "chain_of_custody.sign",
    "cycle_event.log",
    "dispatch.view",
  ],
  CLINIC_ADMIN: [
    "contract.read",
    "contract.request_change",
    "clinic.contract.edit",
    "finance.read.own_clinic",
    "user.manage.own_clinic",
    "drf.list",
    "drf.view",
    "invoice.list",
    "invoice.view",
  ],
  CLINIC_EMBRYOLOGIST: [
    "cycle.list",
    "cycle.view",
    "cycle.log_event",
    "cohort.view",
    "cohort.edit_disposition",
    "cycle_event.log",
    "drf.list",
    "drf.view",
  ],
  CLINIC_WITNESS: [
    "witness.attest.any",
    "cycle.view",
    "cohort.view",
  ],
  BANK_DONOR_COORD: [
    "donor.create",
    "donor.read",
    "donor.update",
    "donor.list",
    "donor.view",
    "donor.consent.capture",
    "donor.screening.enter",
    "donor.defer",
    "donor.undefer",
    "donor.reject",
    "donor.phase.advance",
    "donor.appointment.manage",
  ],
  BANK_ANDROLOGY_TECH: [
    "sample.create",
    "sample.analyze",
    "sample.read",
    "sample.list",
    "sample.view",
    "sample.accession",
    "sample.prep",
    "sample.vial",
    "donor.read",
    "donor.list",
    "donor.view",
  ],
  BANK_SR_ANDROLOGIST: [
    "sample.create",
    "sample.analyze",
    "sample.read",
    "sample.list",
    "sample.view",
    "sample.accession",
    "sample.prep",
    "sample.vial",
    "sample.cryo",
    "sample.qc",
    "sample.post_thaw",
    "sample.close",
    "sample.move",
    "sample.*",
    "gate.qc_a2.approve",
    "gate.qc_a3.approve",
    "gate.qc_a4.approve",
    "gate.qc_a5.approve",
    "donor.list",
    "donor.view",
    "donor.create",
    "donor.consent.capture",
    "donor.screening.enter",
    "donor.defer",
    "donor.undefer",
    "donor.reject",
    "donor.edit",
    "donor.phase.advance",
  ],
  BANK_LAB_HEAD: [
    "donor.gate.approve.any",
    "donor.state.transition",
    "donor.list",
    "donor.view",
    "donor.edit",
    "donor.defer",
    "donor.undefer",
    "donor.reject",
    "gate.*.approve",
    "batch.release",
    "dispatch.exception.approve",
    "sample.read",
    "sample.list",
    "sample.view",
    "sample.qc",
    "sample.close",
    "sample.move",
    "sample.*",
    "drf.list",
    "drf.view",
    "drf.accept",
    "drf.allocate",
    "drf.cancel",
    "dispatch.list",
    "dispatch.view",
    "seedscore.view",
    "report.list",
    "report.view.clinical",
    "report.view.operational",
    "report.run.*",
    "report.export.*",
    "report.favorite",
  ],
  BANK_WITNESS: [
    "witness.attest.any",
    "witness.attest.dispatch",
    "sample.view",
    "sample.list",
  ],
  BANK_CRYOBANK_TECH: [
    "vial.create",
    "vial.move",
    "vial.retrieve",
    "tank.manage",
    "dispatch.pack",
    "sample.list",
    "sample.view",
    "sample.cryo",
    "sample.move",
    "sample.vial",
  ],
  BANK_QC_OFFICER: [
    "sample.list",
    "sample.view",
    "sample.qc",
    "sample.post_thaw",
    "gate.qc_a2.approve",
    "gate.qc_a3.approve",
    "gate.qc_a4.approve",
    "gate.qc_a5.approve",
    "report.list",
    "report.view.compliance",
    "report.run.*",
    "report.export.*",
    "report.favorite",
  ],
  BANK_MATCHING_OPS: ["donor.read", "donor.list", "donor.view"],
  BANK_CLINICAL_REVIEWER: [
    "donor.read.all",
    "donor.gate.approve",
    "donor.list",
    "donor.view",
  ],
  BANK_FINANCE: [
    "challan.*",
    "challan.list",
    "challan.view",
    "invoice.*",
    "invoice.list",
    "invoice.view",
    "invoice.record_payment",
    "invoice.credit_note",
    "invoice.dunning",
    "invoice.void",
    "payment.*",
    "payment.list",
    "payment.reconcile",
    "subscription.create",
    "subscription.view",
    "subscription.modify",
    "subscription.cancel",
    "finance.dashboard",
    "credit_note.create",
    "refund.initiate",
    "dispatch.read.finance",
    "dispatch.list",
    "dispatch.view",
    "drf.list",
    "drf.view",
    "report.list",
    "report.view.finance",
    "report.run.*",
    "report.export.*",
    "report.favorite",
  ],
  BANK_ACCOUNTS_MANAGER: [
    "challan.list",
    "challan.view",
    "invoice.list",
    "invoice.view",
    "invoice.record_payment",
    "invoice.credit_note",
    "invoice.dunning",
    "payment.list",
    "payment.reconcile",
    "subscription.create",
    "subscription.view",
    "subscription.modify",
    "finance.dashboard",
    "report.list",
    "report.view.finance",
    "report.run.*",
    "report.export.*",
    "report.favorite",
  ],
  BANK_CFO: [
    "credit_note.approve.tier2",
    "refund.approve.5L_25L",
    "challan.list",
    "challan.view",
    "invoice.*",
    "invoice.list",
    "invoice.view",
    "invoice.record_payment",
    "invoice.credit_note",
    "invoice.dunning",
    "invoice.void",
    "payment.list",
    "payment.reconcile",
    "subscription.create",
    "subscription.view",
    "subscription.modify",
    "subscription.cancel",
    "finance.dashboard",
    "report.list",
    "report.view.finance",
    "report.view.compliance",
    "report.run.*",
    "report.export.*",
    "report.schedule",
    "report.subscribe",
    "report.snapshot",
    "report.favorite",
  ],
  BANK_SITE_HEAD: [
    "credit_note.approve.tier2",
    "refund.approve.5L_25L",
    "challan.list",
    "challan.view",
    "invoice.list",
    "invoice.view",
    "finance.dashboard",
  ],
  BANK_COMPLIANCE: [
    "donor.read.all.audit",
    "donor.list",
    "donor.view",
    "sample.read.all.audit",
    "gate.*.audit",
    "gst_return.file",
    "tds_form.file",
    "e_invoice.enable",
    "report.list",
    "report.view.compliance",
    "report.view.regulatory",
    "report.run.*",
    "report.export.*",
    "report.snapshot",
    "report.favorite",
  ],
  BANK_DISPATCH_COORD: [
    "dispatch.create",
    "dispatch.state.transition",
    "courier.book",
    "vendor.select",
    "drf.list",
    "drf.view",
    "drf.dispatch",
    "drf.deliver",
    "drf.cancel",
    "dispatch.list",
    "dispatch.view",
    "dispatch.update",
  ],
  BANK_LOGISTICS: [
    "dispatch.create",
    "dispatch.state.transition",
    "courier.book",
    "vendor.select",
    "drf.list",
    "drf.view",
    "drf.dispatch",
    "drf.deliver",
    "drf.cancel",
    "dispatch.list",
    "dispatch.view",
    "dispatch.update",
    "report.list",
    "report.view.logistics",
    "report.run.*",
    "report.export.*",
    "report.favorite",
  ],
  BANK_SITE_ADMIN: [
    "financial_model.assign",
    "payment_terms.override",
    "sample.list",
    "sample.view",
    "sample.qc",
    "sample.close",
    "drf.list",
    "drf.view",
  ],
  BANK_MEDICAL_DIRECTOR: [
    "outcome.view",
    "outcome.trigger_nudges",
    "outcome.close_no_outcome",
    "cycle.list",
    "cycle.view",
    "cohort.view",
    "drf.list",
    "drf.view",
    "donor.list",
    "donor.view",
    "seedscore.view",
    "seedscore.override.tier",
    "lead.config.view",
    "analytics.view",
    "audit.view",
    "report.list",
    "report.view.clinical",
    "report.view.regulatory",
    "report.run.*",
    "report.export.*",
    "report.schedule",
    "report.subscribe",
    "report.favorite",
  ],
  BANK_BRM: [
    "donor.list",
    "donor.view",
    "donor.read",
    "seedscore.view",
    "seedscore.recalc.manual",
    "seedscore.rubric.author",
    "seedscore.question.author",
    "seedscore.rubric.publish",
    "report.list",
    "report.view.clinical",
    "report.view.logistics",
    "report.run.*",
    "report.favorite",
  ],
  BANK_SUPER_ADMIN: [
    "donor.*",
    "donor.list",
    "donor.view",
    "donor.create",
    "donor.consent.capture",
    "donor.screening.enter",
    "donor.defer",
    "donor.undefer",
    "donor.reject",
    "donor.edit",
    "donor.phase.advance",
    "drf.accept",
    "drf.allocate",
    "drf.dispatch",
    "drf.deliver",
    "drf.cancel",
    "dispatch.*",
    "dispatch.list",
    "dispatch.view",
    "dispatch.update",
    "challan.*",
    "challan.list",
    "challan.view",
    "invoice.*",
    "invoice.list",
    "invoice.view",
    "invoice.record_payment",
    "invoice.credit_note",
    "invoice.dunning",
    "invoice.void",
    "payment.list",
    "payment.reconcile",
    "subscription.create",
    "subscription.view",
    "subscription.modify",
    "subscription.cancel",
    "finance.dashboard",
    "user.list",
    "user.role.assign",
    "credit_note.approve.tier3",
    "refund.approve.above_25L",
    "gstin.manage",
    "outcome.view",
    "outcome.trigger_nudges",
    "outcome.close_no_outcome",
    "cycle.list",
    "cycle.view",
    "cycle.log_event",
    "cohort.view",
    "cohort.edit_disposition",
    "seedscore.view",
    "seedscore.recalc.manual",
    "seedscore.rubric.author",
    "seedscore.rubric.publish",
    "seedscore.question.author",
    "seedscore.override.tier",
    "lead.list",
    "lead.view",
    "lead.view.any",
    "lead.view.own",
    "lead.view.assigned_for_counselling",
    "lead.view.for_own_clinic",
    "lead.create",
    "lead.intake",
    "lead.intake.api",
    "lead.assign",
    "lead.reassign",
    "lead.claim",
    "lead.convert",
    "lead.convert.donor",
    "lead.convert.recipient",
    "lead.convert.approve",
    "lead.archive",
    "lead.unarchive",
    "lead.reactivate",
    "lead.merge",
    "lead.edit.limited",
    "lead.purge",
    "lead.export",
    "duplicate.review",
    "assignment.override",
    "analytics.view",
    "audit.view",
    "audit.export",
    "audit.integrity.verify",
    "lead.config.view",
    "lead.config.propose",
    "lead.config.approve",
    "telecaller.dashboard",
    "telecaller.queue",
    "telecaller.disposition",
    "telecaller.book_counselling",
    "counsellor.dashboard",
    "counsellor.sessions",
    "counsellor.mark_attended",
    "counselling.book",
    "counselling.reschedule",
    "counselling.cancel",
    "lead.disposition",
    "lead.note.add",
    "follow_up.create",
    "follow_up.update.own",
    "follow_up.update.any",
    "follow_up.complete.own",
    "follow_up.cancel.own",
    "follow_up.cancel.any",
    "follow_up.reschedule",
    "follow_up.list",
    "dnc.list",
    "dnc.view",
    "dnc.check",
    "dnc.add",
    "dnc.remove",
    "marketing.dashboard",
    "marketing.analytics",
    "ops.qa_sample",
    "crm.sync.manual",
    "crm.sync.retry",
    "report.*",
  ],
  TELECALLER: [
    "telecaller.dashboard",
    "telecaller.queue",
    "telecaller.disposition",
    "telecaller.book_counselling",
    "lead.view",
    "lead.view.own",
    "lead.create",
    "lead.edit.limited",
    "lead.claim",
    "lead.convert",
    "lead.convert.donor",
    "lead.convert.recipient",
    "counselling.book",
    "donor.create",
    "lead.disposition",
    "lead.note.add",
    "follow_up.create",
    "follow_up.update.own",
    "follow_up.complete.own",
    "follow_up.cancel.own",
    "follow_up.reschedule",
    "follow_up.list",
    "dnc.list",
    "dnc.view",
    "dnc.check",
    "dnc.add",
  ],
  SR_TELECALLER: [
    "telecaller.dashboard",
    "telecaller.queue",
    "telecaller.disposition",
    "telecaller.book_counselling",
    "lead.view",
    "lead.view.own",
    "lead.create",
    "lead.edit.limited",
    "lead.claim",
    "lead.reassign",
    "lead.reactivate",
    "lead.convert",
    "lead.convert.donor",
    "lead.convert.recipient",
    "counselling.book",
    "donor.create",
    "lead.disposition",
    "lead.note.add",
    "follow_up.create",
    "follow_up.update.own",
    "follow_up.complete.own",
    "follow_up.cancel.own",
    "follow_up.reschedule",
    "follow_up.list",
    "dnc.list",
    "dnc.view",
    "dnc.check",
    "dnc.add",
  ],
  COUNSELLOR: [
    "counsellor.dashboard",
    "counsellor.sessions",
    "counsellor.mark_attended",
    "lead.view",
    "lead.view.assigned_for_counselling",
    "lead.edit.limited",
    "lead.convert.recipient",
    "counselling.session.record",
    "counselling.outcome.record",
    "lead.note.add",
    "follow_up.create",
    "follow_up.update.own",
    "follow_up.complete.own",
    "follow_up.cancel.own",
    "follow_up.reschedule",
    "follow_up.list",
    "dnc.view",
    "dnc.check",
    "counselling.reschedule",
    "counselling.cancel",
  ],
  OPS_MANAGER: [
    "telecaller.dashboard",
    "telecaller.queue",
    "telecaller.disposition",
    "telecaller.book_counselling",
    "counsellor.dashboard",
    "counsellor.sessions",
    "counsellor.mark_attended",
    "lead.list",
    "lead.view",
    "lead.view.any",
    "lead.create",
    "lead.intake",
    "lead.edit.limited",
    "lead.assign",
    "lead.reassign",
    "lead.claim",
    "lead.convert",
    "lead.convert.donor",
    "lead.convert.recipient",
    "lead.convert.approve",
    "lead.archive",
    "lead.unarchive",
    "lead.reactivate",
    "lead.merge",
    "lead.export",
    "duplicate.review",
    "assignment.override",
    "analytics.view",
    "audit.view",
    "ops.qa_sample",
    "qa.sample",
    "dnc.list",
    "dnc.view",
    "dnc.check",
    "dnc.add",
    "dnc.remove",
    "lead.config.view",
    "lead.config.propose",
    "lead.config.approve",
    "lead.disposition",
    "lead.note.add",
    "follow_up.create",
    "follow_up.update.own",
    "follow_up.update.any",
    "follow_up.complete.own",
    "follow_up.cancel.own",
    "follow_up.cancel.any",
    "follow_up.reschedule",
    "follow_up.list",
    "counselling.book",
    "counselling.reschedule",
    "counselling.cancel",
    "counselling.session.record",
    "counselling.outcome.record",
    "donor.create",
    "report.list",
    "report.view.*",
    "report.run.*",
    "report.favorite",
    "report.schedule",
    "report.subscribe",
  ],
  MARKETING_MANAGER: [
    "marketing.dashboard",
    "marketing.analytics",
    "lead.list",
    "lead.view",
    "lead.view.any",
    "lead.export",
    "dnc.view",
    "lead.config.view",
    "lead.config.propose",
    "lead.config.approve",
    "campaign.view",
    "campaign.create",
    "campaign.edit",
    "campaign.activate",
    "campaign.end",
    "analytics.view",
    "audit.view",
    "notification.template.propose",
    "notification.template.approve",
    "notification.log.view",
    "report.list",
    "report.view.logistics",
    "report.view.operational",
    "report.run.*",
    "report.favorite",
  ],
  CRM_ADMIN: [
    "crm.sync.manual",
    "crm.sync.retry",
    "crm.sync.monitor",
    "lead.config.view",
    "audit.view",
  ],
  L2_IVF_CLINICIAN: [
    "cycle_event.log",
    "cycle_outcome.log",
    "cycle.list",
    "cycle.view",
    "cycle.log_event",
    "cohort.view",
  ],
  L2_EMBRYOLOGIST: [
    "cycle_event.log",
    "cycle.list",
    "cycle.view",
    "cycle.log_event",
    "cohort.view",
    "cohort.edit_disposition",
  ],
  L2_SR_EMBRYOLOGIST: [
    "cycle_event.log",
    "gate.*.approve",
    "cycle.list",
    "cycle.view",
    "cycle.log_event",
    "cohort.view",
    "cohort.edit_disposition",
  ],
  L2_LAB_HEAD: ["gate.*.approve", "batch.release", "cycle.view", "cohort.view"],
};

export function permissionGranted(
  held: Set<Permission> | Permission[],
  required: Permission,
): boolean {
  const set = held instanceof Set ? held : new Set(held);
  if (set.has(required)) return true;
  if (set.has("*")) return true;

  for (const perm of set) {
    if (!perm.endsWith(".*")) continue;
    const prefix = perm.slice(0, -1);
    if (required.startsWith(prefix) || required === perm) return true;
  }
  return false;
}

/** 05 column MARKETING_MGR maps to Prisma `MARKETING_MANAGER`. */
export function canonicalizeUserRole(role: string): UserRole {
  if (role === "MARKETING_MGR") return "MARKETING_MANAGER";
  if (role === "SUPER_ADMIN") return "BANK_SUPER_ADMIN";
  return role as UserRole;
}

export function permissionsForRoles(roles: UserRole[] | readonly string[]): Permission[] {
  return [
    ...new Set(
      roles.flatMap((role) => ROLE_PERMISSIONS[canonicalizeUserRole(role)] ?? []),
    ),
  ];
}

export function holdsLeadViewPermission(roles: readonly string[]): boolean {
  const held = permissionsForRoles(roles);
  return (
    permissionGranted(held, "lead.view.any") ||
    permissionGranted(held, "lead.view.own") ||
    permissionGranted(held, "lead.view.assigned_for_counselling") ||
    permissionGranted(held, "lead.view.for_own_clinic") ||
    permissionGranted(held, "lead.view") ||
    permissionGranted(held, "lead.list")
  );
}

export function holdsLeadViewAny(roles: readonly string[]): boolean {
  const held = permissionsForRoles(roles);
  return permissionGranted(held, "lead.view.any") || permissionGranted(held, "lead.list");
}

export type PortalKind =
  | "admin"
  | "clinic"
  | "donor"
  | "recipient"
  | "telecaller"
  | "counsellor";

export function portalForRole(role: UserRole): PortalKind {
  if (role === "DONOR") return "donor";
  if (role === "RECIPIENT") return "recipient";
  if (role === "TELECALLER" || role === "SR_TELECALLER") return "telecaller";
  if (role === "COUNSELLOR") return "counsellor";
  if (role.startsWith("CLINIC_") || role.startsWith("L2_")) return "clinic";
  return "admin";
}

export function portalHome(portal: PortalKind): string {
  switch (portal) {
    case "admin":
      return "/admin";
    case "clinic":
      return "/clinic";
    case "donor":
      return "/donor";
    case "recipient":
      return "/recipient";
    case "telecaller":
      return "/telecaller/dashboard";
    case "counsellor":
      return "/counsellor/dashboard";
  }
}

export function portalsForRoles(roles: UserRole[]): PortalKind[] {
  return [...new Set(roles.map(portalForRole))];
}
