import { UserRole } from "@prisma/client";

/**
 * Permission strings follow role.action.resource from user_roles_rbac.md.
 * Safe for client + server (no Next/Prisma imports).
 */
export type Permission = string;

export type Role = UserRole;

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  DONOR: [
    "own_profile.read.update",
    "appointment.schedule",
    "consent.sign",
    "honorarium.read.own",
    "document.upload.own",
    "withdrawal.initiate",
    "ae.report",
  ],
  RECIPIENT: [
    "own_case.read",
    "package.select",
    "consent.sign",
    "profile.browse",
    "payment.pay",
    "invoice.read.own",
    "cycle_status.read.own",
  ],
  CLINIC_DOCTOR: [
    "drf.create",
    "drf.sign",
    "drf.list",
    "drf.view",
    "cycle_outcome.log",
  ],
  CLINIC_COORDINATOR: [
    "recipient.create",
    "drf.track",
    "drf.communicate",
    "drf.create",
    "drf.list",
    "drf.view",
    "invoice.list",
    "invoice.view",
  ],
  CLINIC_NURSE: [
    "dispatch.receive",
    "chain_of_custody.sign",
    "cycle_event.log",
    "dispatch.view",
  ],
  CLINIC_ADMIN: [
    "contract.read",
    "contract.request_change",
    "clinic.contract.edit",
    "finance.read.own_clinic",
    "user.manage.own_clinic",
    "drf.list",
    "drf.view",
    "invoice.list",
    "invoice.view",
  ],
  BANK_DONOR_COORD: [
    "donor.create",
    "donor.read",
    "donor.update",
    "donor.list",
    "donor.view",
    "donor.consent.capture",
    "donor.screening.enter",
    "donor.defer",
    "donor.reject",
    "donor.phase.advance",
    "donor.appointment.manage",
  ],
  BANK_ANDROLOGY_TECH: [
    "sample.create",
    "sample.analyze",
    "sample.read",
    "sample.list",
    "sample.view",
    "sample.accession",
    "sample.prep",
    "sample.vial",
    "donor.read",
    "donor.list",
    "donor.view",
  ],
  BANK_SR_ANDROLOGIST: [
    "sample.create",
    "sample.analyze",
    "sample.read",
    "sample.list",
    "sample.view",
    "sample.accession",
    "sample.prep",
    "sample.vial",
    "sample.cryo",
    "sample.qc",
    "sample.post_thaw",
    "sample.close",
    "sample.move",
    "sample.*",
    "gate.qc_a2.approve",
    "gate.qc_a3.approve",
    "gate.qc_a4.approve",
    "gate.qc_a5.approve",
    "donor.list",
    "donor.view",
    "donor.create",
    "donor.consent.capture",
    "donor.screening.enter",
    "donor.defer",
    "donor.reject",
    "donor.phase.advance",
  ],
  BANK_LAB_HEAD: [
    "donor.gate.approve.any",
    "donor.state.transition",
    "donor.list",
    "donor.view",
    "gate.*.approve",
    "batch.release",
    "dispatch.exception.approve",
    "sample.read",
    "sample.list",
    "sample.view",
    "sample.qc",
    "sample.close",
    "sample.move",
    "sample.*",
    "drf.list",
    "drf.view",
    "drf.accept",
    "drf.allocate",
    "drf.cancel",
    "dispatch.list",
    "dispatch.view",
  ],
  BANK_WITNESS: [
    "witness.attest.any",
    "witness.attest.dispatch",
    "sample.view",
    "sample.list",
  ],
  BANK_CRYOBANK_TECH: [
    "vial.create",
    "vial.move",
    "vial.retrieve",
    "tank.manage",
    "dispatch.pack",
    "sample.list",
    "sample.view",
    "sample.cryo",
    "sample.move",
    "sample.vial",
  ],
  BANK_QC_OFFICER: [
    "sample.list",
    "sample.view",
    "sample.qc",
    "sample.post_thaw",
    "gate.qc_a2.approve",
    "gate.qc_a3.approve",
    "gate.qc_a4.approve",
    "gate.qc_a5.approve",
  ],
  BANK_MATCHING_OPS: ["donor.read", "donor.list", "donor.view"],
  BANK_CLINICAL_REVIEWER: [
    "donor.read.all",
    "donor.gate.approve",
    "donor.list",
    "donor.view",
  ],
  BANK_FINANCE: [
    "challan.*",
    "challan.list",
    "challan.view",
    "invoice.*",
    "invoice.list",
    "invoice.view",
    "invoice.record_payment",
    "invoice.credit_note",
    "invoice.dunning",
    "invoice.void",
    "payment.*",
    "payment.list",
    "payment.reconcile",
    "subscription.create",
    "subscription.view",
    "subscription.modify",
    "subscription.cancel",
    "finance.dashboard",
    "credit_note.create",
    "refund.initiate",
    "dispatch.read.finance",
    "dispatch.list",
    "dispatch.view",
    "drf.list",
    "drf.view",
  ],
  BANK_ACCOUNTS_MANAGER: [
    "challan.list",
    "challan.view",
    "invoice.list",
    "invoice.view",
    "invoice.record_payment",
    "invoice.credit_note",
    "invoice.dunning",
    "payment.list",
    "payment.reconcile",
    "subscription.create",
    "subscription.view",
    "subscription.modify",
    "finance.dashboard",
  ],
  BANK_CFO: [
    "credit_note.approve.tier2",
    "refund.approve.5L_25L",
    "challan.list",
    "challan.view",
    "invoice.*",
    "invoice.list",
    "invoice.view",
    "invoice.record_payment",
    "invoice.credit_note",
    "invoice.dunning",
    "invoice.void",
    "payment.list",
    "payment.reconcile",
    "subscription.create",
    "subscription.view",
    "subscription.modify",
    "subscription.cancel",
    "finance.dashboard",
  ],
  BANK_SITE_HEAD: [
    "credit_note.approve.tier2",
    "refund.approve.5L_25L",
    "challan.list",
    "challan.view",
    "invoice.list",
    "invoice.view",
    "finance.dashboard",
  ],
  BANK_COMPLIANCE: [
    "donor.read.all.audit",
    "donor.list",
    "donor.view",
    "sample.read.all.audit",
    "gate.*.audit",
    "gst_return.file",
    "tds_form.file",
    "e_invoice.enable",
  ],
  BANK_DISPATCH_COORD: [
    "dispatch.create",
    "dispatch.state.transition",
    "courier.book",
    "vendor.select",
    "drf.list",
    "drf.view",
    "drf.dispatch",
    "drf.deliver",
    "drf.cancel",
    "dispatch.list",
    "dispatch.view",
    "dispatch.update",
  ],
  BANK_LOGISTICS: [
    "dispatch.create",
    "dispatch.state.transition",
    "courier.book",
    "vendor.select",
    "drf.list",
    "drf.view",
    "drf.dispatch",
    "drf.deliver",
    "drf.cancel",
    "dispatch.list",
    "dispatch.view",
    "dispatch.update",
  ],
  BANK_SITE_ADMIN: [
    "financial_model.assign",
    "payment_terms.override",
    "sample.list",
    "sample.view",
    "sample.qc",
    "sample.close",
    "drf.list",
    "drf.view",
  ],
  BANK_SUPER_ADMIN: [
    "donor.*",
    "donor.list",
    "donor.view",
    "donor.create",
    "donor.consent.capture",
    "donor.screening.enter",
    "donor.defer",
    "donor.reject",
    "donor.phase.advance",
    "sample.*",
    "sample.list",
    "sample.view",
    "sample.accession",
    "sample.analyze",
    "sample.prep",
    "sample.vial",
    "sample.cryo",
    "sample.qc",
    "sample.post_thaw",
    "sample.close",
    "sample.move",
    "drf.*",
    "drf.list",
    "drf.view",
    "drf.create",
    "drf.accept",
    "drf.allocate",
    "drf.dispatch",
    "drf.deliver",
    "drf.cancel",
    "dispatch.*",
    "dispatch.list",
    "dispatch.view",
    "dispatch.update",
    "challan.*",
    "challan.list",
    "challan.view",
    "invoice.*",
    "invoice.list",
    "invoice.view",
    "invoice.record_payment",
    "invoice.credit_note",
    "invoice.dunning",
    "invoice.void",
    "payment.list",
    "payment.reconcile",
    "subscription.create",
    "subscription.view",
    "subscription.modify",
    "subscription.cancel",
    "finance.dashboard",
    "user.list",
    "user.role.assign",
    "credit_note.approve.tier3",
    "refund.approve.above_25L",
    "gstin.manage",
  ],
  L2_IVF_CLINICIAN: ["cycle_event.log", "cycle_outcome.log"],
  L2_EMBRYOLOGIST: ["cycle_event.log"],
  L2_SR_EMBRYOLOGIST: ["cycle_event.log", "gate.*.approve"],
  L2_LAB_HEAD: ["gate.*.approve", "batch.release"],
};

export function permissionGranted(
  held: Set<Permission> | Permission[],
  required: Permission,
): boolean {
  const set = held instanceof Set ? held : new Set(held);
  if (set.has(required)) return true;
  if (set.has("*")) return true;

  for (const perm of set) {
    if (!perm.endsWith(".*")) continue;
    const prefix = perm.slice(0, -1);
    if (required.startsWith(prefix) || required === perm) return true;
  }
  return false;
}

export function permissionsForRoles(roles: UserRole[]): Permission[] {
  return [...new Set(roles.flatMap((role) => ROLE_PERMISSIONS[role] ?? []))];
}

export type PortalKind = "admin" | "clinic" | "donor" | "recipient";

export function portalForRole(role: UserRole): PortalKind {
  if (role === "DONOR") return "donor";
  if (role === "RECIPIENT") return "recipient";
  if (role.startsWith("CLINIC_") || role.startsWith("L2_")) return "clinic";
  return "admin";
}

export function portalHome(portal: PortalKind): string {
  switch (portal) {
    case "admin":
      return "/admin";
    case "clinic":
      return "/clinic";
    case "donor":
      return "/donor";
    case "recipient":
      return "/recipient";
  }
}

export function portalsForRoles(roles: UserRole[]): PortalKind[] {
  return [...new Set(roles.map(portalForRole))];
}
