import "server-only";

import { stringify } from "csv-stringify/sync";

import type { ColumnDefinition, ReportFilters, ReportRow } from "@/lib/reports/types";

export type CsvExportInput = {
  reportName: string;
  generatedAtUtc: string;
  generatedAtIst: string;
  generatedBy: string;
  filters: ReportFilters;
  rowCount: number;
  columns: ColumnDefinition[];
  rows: ReportRow[];
};

export function toCsv(input: CsvExportInput): string {
  const meta = [
    `# Report: ${input.reportName}`,
    `# Generated (UTC): ${input.generatedAtUtc}`,
    `# Generated (IST): ${input.generatedAtIst}`,
    `# Generated by: ${input.generatedBy}`,
    `# Filters: ${JSON.stringify(input.filters)}`,
    `# Row count: ${input.rowCount}`,
  ].join("\n");

  const headers = input.columns.map((c) => c.label);
  const keys = input.columns.map((c) => c.key);
  const data = input.rows.map((row) =>
    keys.map((k) => {
      const v = row[k];
      if (v === null || v === undefined) return "";
      if (v instanceof Date) return v.toISOString();
      return String(v);
    }),
  );

  const body = stringify([headers, ...data]);
  return `${meta}\n${body}`;
}
