import "server-only";

import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Image,
  renderToBuffer,
} from "@react-pdf/renderer";

import type { ColumnDefinition, ReportFilters, ReportRow } from "@/lib/reports/types";

export type PdfExportInput = {
  reportName: string;
  generatedAtUtc: string;
  generatedAtIst: string;
  generatedBy: string;
  filters: ReportFilters;
  rowCount: number;
  columns: ColumnDefinition[];
  rows: ReportRow[];
  chartPng?: Buffer | null;
};

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 9, fontFamily: "Helvetica" },
  brand: { fontSize: 16, color: "#064e3b", marginBottom: 4, fontFamily: "Helvetica-Bold" },
  title: { fontSize: 14, marginBottom: 8, fontFamily: "Helvetica-Bold" },
  meta: { marginBottom: 4, color: "#444" },
  chart: { width: 520, height: 220, marginVertical: 12 },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#064e3b",
    color: "#fff",
    paddingVertical: 4,
    paddingHorizontal: 2,
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: "#ddd",
    paddingVertical: 3,
    paddingHorizontal: 2,
  },
  cell: { flex: 1, paddingHorizontal: 2 },
  footer: { position: "absolute", bottom: 24, left: 36, right: 36, fontSize: 8, color: "#666" },
});

function cellValue(v: unknown): string {
  if (v === null || v === undefined) return "—";
  if (v instanceof Date) return v.toISOString().slice(0, 10);
  return String(v);
}

function ReportPdfDocument({ input }: { input: PdfExportInput }) {
  const cols = input.columns.slice(0, 6);
  const chartSrc =
    input.chartPng && input.chartPng.length > 0
      ? `data:image/png;base64,${input.chartPng.toString("base64")}`
      : null;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.brand}>LifeSeed ART Bank</Text>
        <Text style={styles.title}>{input.reportName}</Text>
        <Text style={styles.meta}>Generated (UTC): {input.generatedAtUtc}</Text>
        <Text style={styles.meta}>Generated (IST): {input.generatedAtIst}</Text>
        <Text style={styles.meta}>Generated by: {input.generatedBy}</Text>
        <Text style={styles.meta}>Filters: {JSON.stringify(input.filters)}</Text>
        <Text style={styles.meta}>Row count: {input.rowCount}</Text>

        {chartSrc ? <Image style={styles.chart} src={chartSrc} /> : null}

        <View style={styles.tableHeader}>
          {cols.map((c) => (
            <Text key={c.key} style={styles.cell}>
              {c.label}
            </Text>
          ))}
        </View>
        {input.rows.slice(0, 40).map((row, idx) => (
          <View key={idx} style={styles.tableRow} wrap={false}>
            {cols.map((c) => (
              <Text key={c.key} style={styles.cell}>
                {cellValue(row[c.key])}
              </Text>
            ))}
          </View>
        ))}
        {input.rowCount > 40 ? (
          <Text style={styles.meta}>Showing first 40 of {input.rowCount} rows.</Text>
        ) : null}
        <Text style={styles.footer}>
          LifeSeed Reports · confidential · DPDP / ART Act controlled
        </Text>
      </Page>
    </Document>
  );
}

export async function toPdf(input: PdfExportInput): Promise<Buffer> {
  const element = <ReportPdfDocument input={input} />;
  const buf = await renderToBuffer(element);
  return Buffer.from(buf);
}
