import "server-only";

import ExcelJS from "exceljs";

import type { ColumnDefinition, ReportFilters, ReportRow } from "@/lib/reports/types";

export type XlsxExportInput = {
  reportName: string;
  generatedAtUtc: string;
  generatedAtIst: string;
  generatedBy: string;
  filters: ReportFilters;
  rowCount: number;
  columns: ColumnDefinition[];
  rows: ReportRow[];
};

export async function toXlsx(input: XlsxExportInput): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "LifeSeed Reports";
  wb.created = new Date();

  const meta = wb.addWorksheet("Metadata");
  meta.addRow(["Report", input.reportName]);
  meta.addRow(["Generated (UTC)", input.generatedAtUtc]);
  meta.addRow(["Generated (IST)", input.generatedAtIst]);
  meta.addRow(["Generated by", input.generatedBy]);
  meta.addRow(["Filters", JSON.stringify(input.filters)]);
  meta.addRow(["Row count", input.rowCount]);
  meta.getColumn(1).width = 22;
  meta.getColumn(2).width = 60;

  const sheet = wb.addWorksheet("Data");
  sheet.addRow(input.columns.map((c) => c.label));
  const header = sheet.getRow(1);
  header.font = { bold: true };
  header.fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: "FF064E3B" },
  };
  header.font = { bold: true, color: { argb: "FFFFFFFF" } };

  for (const row of input.rows) {
    sheet.addRow(
      input.columns.map((c) => {
        const v = row[c.key];
        if (v === null || v === undefined) return "";
        if (v instanceof Date) return v.toISOString();
        if (typeof v === "object") return JSON.stringify(v);
        return v as string | number | boolean;
      }),
    );
  }

  input.columns.forEach((col, i) => {
    const column = sheet.getColumn(i + 1);
    const sample = String(col.label);
    column.width = Math.min(40, Math.max(12, sample.length + 4));
  });

  const buf = await wb.xlsx.writeBuffer();
  return Buffer.from(buf);
}
